### ISSUE TITLE
How to use this plugin

### ISSUE THREAD

**Issue by bramhechatejas** [svrooij/rest-api-filter-fields#14]
Hi,

This is okay, but nowhere you have mentioned how to use this plugin. In what format api call should be made in order to fetch filtered data? Please let us know the same

Thanks,

**Comment by svrooij** [comment]
You take the regular api endpoint from [the api docs](https://developer.wordpress.org/rest-api/reference/posts/) like `http://your.wordpress.com/wp-json/wp/v2/posts` and then you add `?fields=` with the fields you want.

`http://your.wp.com/wp-json/wp/v2/posts?fields=id,name`

**Comment by pedropolisenso** [comment]
How to can i apply this plugin to my custom route. For exemple, this plugin understand the route /ap-json/wp/v2/..., but I want my route: /wp-json/api/v1/...
