### ISSUE TITLE
Category post filter doesn't seems working

### ISSUE THREAD

**Issue by vyasdharmesh** [svrooij/rest-api-filter-fields#21]
Hi There,
Thanks for this plugin.
I have installed plugin on my WP 5.4.2 website

I basically would like to fetch all posts belongs to one particular category
Category post link is: http://www.mojemoj.com/category/articles

I understood that Json API link should be http://www.mojemoj.com/wp-json/wp/v2/posts?categories=30

Even I tried with slug : http://www.mojemoj.com/wp-json/wp/v2/posts?slug=articles

But it pull out all posts and filter seems not working.

Can you help, if I am doing something wrong?

**Comment by svrooij** [comment]
It seems like wordpress [integrated](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/) their own version. So you should try the `_fields` parameter.
