### ISSUE TITLE
add featuredmedia as filter

### ISSUE THREAD

**Issue by chief-nerd** [svrooij/rest-api-filter-fields#5]
Missing ability to add featuredmedia or _embedded objects in filter call  
e.g in Node
`response[i]._embedded["https://api.w.org/featuredmedia"][0].source_url;`

**Comment by ChazUK** [comment]
+1

**Comment by svrooij** [comment]
@JakobReiter @ChazUK This if fixed as of version 1.0.5 with the following parameter: `http://your.website.com/wp-json/wp/v2/posts?_embed&fields=_embedded.wp:featuredmedia.first.source_url`

Please let me know what you thing of [buy me a beer :beer:](https://svrooij.nl/buy-me-a-beer/)
