### ISSUE TITLE
didnt works on my wp 4.7.3 site

### ISSUE THREAD

**Issue by RonyRunrun** [svrooij/rest-api-filter-fields#8]
i already installed this plugin but when i try to call filter it show like default../posts

**Comment by svrooij** [comment]
@RonyRunrun could you provide me with an address of your website?

I just checked on my own website, where is just seems to work. [filtered response](https://svrooij.nl/wp-json/wp/v2/posts?per_page=5&fields=title,content.rendered,link)

It their still seems to be a problem, could you provide me with a list of plugins installed, so I can try to investigate the problem.

**Comment by RonyRunrun** [comment]
its worked now..after im updating with latest version.. but how can i get all posts?
or how can i use filter posts per page?

**Comment by svrooij** [comment]
[here](https://developer.wordpress.org/rest-api/reference/posts/#list-posts) is the documentation on the API (for listing posts). This plugin adds an extra `fields` get parameter, so you can choose what parameters you want for each post.

**Comment by RonyRunrun** [comment]
I try tp call post?per_page=20..it work..but when i add post?per_page=20?fields=id,title.rendered,content ..its doesn't work..
My link http://www.opinianda.com/wp-json/wp/v2/posts?per_page=20

**Comment by svrooij** [comment]
Have you tried putting an `&` between `per_page=20` and `fields=title,link` instead of a `?` like [..posts?per_page=20&fields=link,title,content.rendered](http://www.opinianda.com/wp-json/wp/v2/posts?per_page=20&fields=link,title,content.rendered)
