### ISSUE TITLE
Should this work on the /users endpoint?

### ISSUE THREAD

**Issue by ecurtis** [svrooij/rest-api-filter-fields#9]
I just tried this on the users endpoint with:
http://...url.../wp-json/wp/v2/users?fields=id

But the full response still returns. It does work on the posts endpoint.

**Comment by svrooij** [comment]
Hello Eric @ecurtis,

The plugin is added as a filter to different types [here](https://github.com/svrooij/rest-api-filter-fields/blob/master/rest-api-filter-fields/includes/class-rest-api-filter-fields.php#L56), the post types and the taxonomies are above that. As of [4.7.0](https://developer.wordpress.org/reference/hooks/rest_prepare_user/) it also seems possible to do this for users. 
Could you verify that it works on the user endpoint if you add this line to the rest prepare statements?
`add_filter('rest_prepare_user',array($this,'filter_magic'),20,3);`

**Comment by ecurtis** [comment]
That worked. Thank you

**Comment by svrooij** [comment]
I will include this in the next release. If you want to thank me for this plugin, you [can buy me a beer here](https://svrooij.nl/buy-me-a-beer/)
